### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by brandleesee**

### CODE REVIEW

**Comment by tuxor1337** [comment]
It's not necessary to reload the gnome shell to activate an extension. And it's also unnecessary to re-enable an extension in gnome-tweak-tool when it's already been enabled using `gnome-shell-extension-tool`. I suspect that this is not working for you which means that your setup is buggy. Which version of GNOME are you using?

**Comment by brandleesee** [comment]
GNOME Shell 3.18.5

I followed your steps perfectly and gnome-tweak-tool --> extensions did not display the Hide Top Bar extension.

On executing: <code>Alt+F2 r {Enter}</code> the Extension becave available in the Tweak Tool.

**Comment by tuxor1337** [comment]
You are right: Extensions that are manually (!) added to `~/.local/share/gnome-shell/extensions` during runtime seem to be ignored completely by GNOME Shell. This does not affect extensions added from extensions.gnome.org. I added instructions for this in the README. Thanks for your hint!

**Comment by brandleesee** [comment]
You're welcome!
Glad I could help.
Cheers.

**Pull request closed without merging**
