### PR TITLE
Add 42 since it works there too

### PR DESCRIPTION
**Pull request by shemgp**
Tested on Ubuntu Jammy Jellyfish + GNOME PPA with gnome-shell 42~alpha.

Preferences works too.

Thanks for this nice and useful extension.

### CODE REVIEW

**Comment by tuxor1337** [comment]
Thanks for testing!

**Comment by JingMatrix** [comment]
I have to say, not really work, it seems we need to change the Settings.ui.
See my screenshot
Screenshot from 2022-03-10 12-57-52

**Comment by logrusx** [comment]
Same issue here.

**Comment by JingMatrix** [comment]
Also, it causes a problem in alacritty, see description there
https://github.com/alacritty/alacritty/issues/5967

**Comment by logrusx** [comment]
I'm not sure if it's because of 42 but I think it is, as I didn't observe it before, the topbar doesn't hide after I move the mouse away.

**Comment by tuxor1337** [comment]
@logrusx This is addressed in #354

**Comment by JingMatrix** [comment]
> Also, it causes a problem in alacritty, see description there [alacritty/alacritty#5967](https://github.com/alacritty/alacritty/issues/5967)

I was wrong, it's designed by purpose: 
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/master/stable/xdg-shell/xdg-shell.xml#L[988]

```
If the fullscreened surface is not opaque, the compositor must make
	sure that other screen content not part of the same surface tree (made
	up of subsurfaces, popups or similarly coupled surfaces) are not
	visible below the fullscreened surface.
```

**Pull request merged**
